//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landscapes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LandscapesEntities : DbContext
    {
        public LandscapesEntities()
            : base("name=LandscapesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ls_User> Ls_User { get; set; }
        public DbSet<Ls_SubCategory> Ls_SubCategory { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Ls_ChildCategory> Ls_ChildCategory { get; set; }
    }
}
