//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landscapes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ls_SubCategory
    {
        public int SubCategory_Id { get; set; }
        public string SubCategory_Name { get; set; }
        public string Added_by { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> Added_Date { get; set; }
        public Nullable<int> Category_Id { get; set; }
    }
}
