//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace Excel.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsSubjectPrescreenPlusSoap", Namespace="https://webservice.drivershistory.com/currentVersion6")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResults))]
    public partial class wsSubjectPrescreenPlus : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SubjectSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubjectSearchBasicOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsSubjectPrescreenPlus() {
            this.Url = global::Excel.Properties.Settings.Default.Excel_WebReference_wsSubjectPrescreenPlus;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SubjectSearchCompletedEventHandler SubjectSearchCompleted;
        
        /// <remarks/>
        public event SubjectSearchBasicCompletedEventHandler SubjectSearchBasicCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.drivershistory.com/currentVersion6/SubjectSearch", RequestNamespace="https://webservice.drivershistory.com/currentVersion6", ResponseNamespace="https://webservice.drivershistory.com/currentVersion6", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SubjectSearchResults SubjectSearch([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string LicenseKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SearchID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Reference, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TrackingNumber, [System.Xml.Serialization.XmlElementAttribute("ProductCodes", IsNullable=true)] string[] ProductCodes, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string QueryType, [System.Xml.Serialization.XmlElementAttribute("Subject", IsNullable=true)] iSubject[] Subject, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string PolicyState, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string LookbackStartDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string LookbackEndDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DHIExpansionXML, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string UsePurposeCode) {
            object[] results = this.Invoke("SubjectSearch", new object[] {
                        LicenseKey,
                        SearchID,
                        Reference,
                        TrackingNumber,
                        ProductCodes,
                        QueryType,
                        Subject,
                        PolicyState,
                        LookbackStartDate,
                        LookbackEndDate,
                        DHIExpansionXML,
                        UsePurposeCode});
            return ((SubjectSearchResults)(results[0]));
        }
        
        /// <remarks/>
        public void SubjectSearchAsync(string LicenseKey, string SearchID, string Reference, string TrackingNumber, string[] ProductCodes, string QueryType, iSubject[] Subject, string PolicyState, string LookbackStartDate, string LookbackEndDate, string DHIExpansionXML, string UsePurposeCode) {
            this.SubjectSearchAsync(LicenseKey, SearchID, Reference, TrackingNumber, ProductCodes, QueryType, Subject, PolicyState, LookbackStartDate, LookbackEndDate, DHIExpansionXML, UsePurposeCode, null);
        }
        
        /// <remarks/>
        public void SubjectSearchAsync(string LicenseKey, string SearchID, string Reference, string TrackingNumber, string[] ProductCodes, string QueryType, iSubject[] Subject, string PolicyState, string LookbackStartDate, string LookbackEndDate, string DHIExpansionXML, string UsePurposeCode, object userState) {
            if ((this.SubjectSearchOperationCompleted == null)) {
                this.SubjectSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubjectSearchOperationCompleted);
            }
            this.InvokeAsync("SubjectSearch", new object[] {
                        LicenseKey,
                        SearchID,
                        Reference,
                        TrackingNumber,
                        ProductCodes,
                        QueryType,
                        Subject,
                        PolicyState,
                        LookbackStartDate,
                        LookbackEndDate,
                        DHIExpansionXML,
                        UsePurposeCode}, this.SubjectSearchOperationCompleted, userState);
        }
        
        private void OnSubjectSearchOperationCompleted(object arg) {
            if ((this.SubjectSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubjectSearchCompleted(this, new SubjectSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://webservice.drivershistory.com/currentVersion6/SubjectSearchBasic", RequestNamespace="https://webservice.drivershistory.com/currentVersion6", ResponseNamespace="https://webservice.drivershistory.com/currentVersion6", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SubjectSearchResults SubjectSearchBasic(
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string LicenseKey, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string SearchId, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Reference, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string QueryType, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string FirstName, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string MiddleName, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string LastName, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Suffix, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Gender, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DLNumber, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DLState, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DLCountry, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string BirthYear, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string BirthMonth, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string BirthDay, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Address1, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Address2, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string City, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string StateCode, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Zip, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string PolicyState, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string LookbackStartDate, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string LookbackEndDate, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string DHIExpansionXml) {
            object[] results = this.Invoke("SubjectSearchBasic", new object[] {
                        LicenseKey,
                        SearchId,
                        Reference,
                        QueryType,
                        FirstName,
                        MiddleName,
                        LastName,
                        Suffix,
                        Gender,
                        DLNumber,
                        DLState,
                        DLCountry,
                        BirthYear,
                        BirthMonth,
                        BirthDay,
                        Address1,
                        Address2,
                        City,
                        StateCode,
                        Zip,
                        PolicyState,
                        LookbackStartDate,
                        LookbackEndDate,
                        DHIExpansionXml});
            return ((SubjectSearchResults)(results[0]));
        }
        
        /// <remarks/>
        public void SubjectSearchBasicAsync(
                    string LicenseKey, 
                    string SearchId, 
                    string Reference, 
                    string QueryType, 
                    string FirstName, 
                    string MiddleName, 
                    string LastName, 
                    string Suffix, 
                    string Gender, 
                    string DLNumber, 
                    string DLState, 
                    string DLCountry, 
                    string BirthYear, 
                    string BirthMonth, 
                    string BirthDay, 
                    string Address1, 
                    string Address2, 
                    string City, 
                    string StateCode, 
                    string Zip, 
                    string PolicyState, 
                    string LookbackStartDate, 
                    string LookbackEndDate, 
                    string DHIExpansionXml) {
            this.SubjectSearchBasicAsync(LicenseKey, SearchId, Reference, QueryType, FirstName, MiddleName, LastName, Suffix, Gender, DLNumber, DLState, DLCountry, BirthYear, BirthMonth, BirthDay, Address1, Address2, City, StateCode, Zip, PolicyState, LookbackStartDate, LookbackEndDate, DHIExpansionXml, null);
        }
        
        /// <remarks/>
        public void SubjectSearchBasicAsync(
                    string LicenseKey, 
                    string SearchId, 
                    string Reference, 
                    string QueryType, 
                    string FirstName, 
                    string MiddleName, 
                    string LastName, 
                    string Suffix, 
                    string Gender, 
                    string DLNumber, 
                    string DLState, 
                    string DLCountry, 
                    string BirthYear, 
                    string BirthMonth, 
                    string BirthDay, 
                    string Address1, 
                    string Address2, 
                    string City, 
                    string StateCode, 
                    string Zip, 
                    string PolicyState, 
                    string LookbackStartDate, 
                    string LookbackEndDate, 
                    string DHIExpansionXml, 
                    object userState) {
            if ((this.SubjectSearchBasicOperationCompleted == null)) {
                this.SubjectSearchBasicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubjectSearchBasicOperationCompleted);
            }
            this.InvokeAsync("SubjectSearchBasic", new object[] {
                        LicenseKey,
                        SearchId,
                        Reference,
                        QueryType,
                        FirstName,
                        MiddleName,
                        LastName,
                        Suffix,
                        Gender,
                        DLNumber,
                        DLState,
                        DLCountry,
                        BirthYear,
                        BirthMonth,
                        BirthDay,
                        Address1,
                        Address2,
                        City,
                        StateCode,
                        Zip,
                        PolicyState,
                        LookbackStartDate,
                        LookbackEndDate,
                        DHIExpansionXml}, this.SubjectSearchBasicOperationCompleted, userState);
        }
        
        private void OnSubjectSearchBasicOperationCompleted(object arg) {
            if ((this.SubjectSearchBasicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubjectSearchBasicCompleted(this, new SubjectSearchBasicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class iSubject {
        
        private string numberField;
        
        private iName[] nameField;
        
        private iPhone[] phoneField;
        
        private iAddress[] addressField;
        
        private iDOB[] dOBField;
        
        private iDriversLicense[] driversLicenseField;
        
        private string genderField;
        
        private string personIDField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public iName[] Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Phone")]
        public iPhone[] Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Address")]
        public iAddress[] Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DOB")]
        public iDOB[] DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DriversLicense")]
        public iDriversLicense[] DriversLicense {
            get {
                return this.driversLicenseField;
            }
            set {
                this.driversLicenseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PersonID {
            get {
                return this.personIDField;
            }
            set {
                this.personIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class iName {
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string nameSuffixField;
        
        private string sourceField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NameSuffix {
            get {
                return this.nameSuffixField;
            }
            set {
                this.nameSuffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class oStandardizedAddress {
        
        private string subjectNumberField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateCodeField;
        
        private string zipField;
        
        private string countryCodeField;
        
        private string sourceField;
        
        private string statusField;
        
        private string typeField;
        
        private string standardizationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SubjectNumber {
            get {
                return this.subjectNumberField;
            }
            set {
                this.subjectNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StandardizationCode {
            get {
                return this.standardizationCodeField;
            }
            set {
                this.standardizationCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class oDriversLicense {
        
        private string numberField;
        
        private string stateCodeField;
        
        private string countryCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class oLicensePlate {
        
        private string numberField;
        
        private string stateCodeField;
        
        private string countryCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class oAddress {
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateCodeField;
        
        private string zipField;
        
        private string countryCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class CustomerSpecificItemType {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class StateSpecificItemType {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class oDriverViolation {
        
        private string courtDateField;
        
        private int dMVPointsField;
        
        private int iNSPointsField;
        
        private int chargeCountField;
        
        private string fNameField;
        
        private string lNameField;
        
        private string mNameField;
        
        private string suffixField;
        
        private string birthYearField;
        
        private string birthMonthField;
        
        private string birthDayField;
        
        private string genderField;
        
        private string eyeColorField;
        
        private string docketField;
        
        private string caseTypeField;
        
        private string summonsField;
        
        private string violationStateCodeField;
        
        private string violationDateField;
        
        private string violationStatuteField;
        
        private string violationDescriptionField;
        
        private string violationAcdCodeField;
        
        private string violationCustomerCodeField;
        
        private string violationEVCField;
        
        private string adjudicatedDateField;
        
        private string adjudicatedStatuteField;
        
        private string adjudicatedDescriptionField;
        
        private string adjudicatedAcdCodeField;
        
        private string adjudicatedCustomerCodeField;
        
        private string adjudicatedEVCField;
        
        private string dispositionField;
        
        private StateSpecificItemType[] stateSpecificField;
        
        private CustomerSpecificItemType[] customerSpecificField;
        
        private string uncomputedStatuteIndicatorField;
        
        private string violationSubRankField;
        
        private string downgradeIndicatorField;
        
        private oAddress addressField;
        
        private oLicensePlate licensePlateField;
        
        private oDriversLicense driversLicenseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CourtDate {
            get {
                return this.courtDateField;
            }
            set {
                this.courtDateField = value;
            }
        }
        
        /// <remarks/>
        public int DMVPoints {
            get {
                return this.dMVPointsField;
            }
            set {
                this.dMVPointsField = value;
            }
        }
        
        /// <remarks/>
        public int INSPoints {
            get {
                return this.iNSPointsField;
            }
            set {
                this.iNSPointsField = value;
            }
        }
        
        /// <remarks/>
        public int ChargeCount {
            get {
                return this.chargeCountField;
            }
            set {
                this.chargeCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FName {
            get {
                return this.fNameField;
            }
            set {
                this.fNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LName {
            get {
                return this.lNameField;
            }
            set {
                this.lNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MName {
            get {
                return this.mNameField;
            }
            set {
                this.mNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BirthYear {
            get {
                return this.birthYearField;
            }
            set {
                this.birthYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BirthMonth {
            get {
                return this.birthMonthField;
            }
            set {
                this.birthMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BirthDay {
            get {
                return this.birthDayField;
            }
            set {
                this.birthDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EyeColor {
            get {
                return this.eyeColorField;
            }
            set {
                this.eyeColorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Docket {
            get {
                return this.docketField;
            }
            set {
                this.docketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CaseType {
            get {
                return this.caseTypeField;
            }
            set {
                this.caseTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Summons {
            get {
                return this.summonsField;
            }
            set {
                this.summonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ViolationStateCode {
            get {
                return this.violationStateCodeField;
            }
            set {
                this.violationStateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ViolationDate {
            get {
                return this.violationDateField;
            }
            set {
                this.violationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ViolationStatute {
            get {
                return this.violationStatuteField;
            }
            set {
                this.violationStatuteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ViolationDescription {
            get {
                return this.violationDescriptionField;
            }
            set {
                this.violationDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ViolationAcdCode {
            get {
                return this.violationAcdCodeField;
            }
            set {
                this.violationAcdCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ViolationCustomerCode {
            get {
                return this.violationCustomerCodeField;
            }
            set {
                this.violationCustomerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ViolationEVC {
            get {
                return this.violationEVCField;
            }
            set {
                this.violationEVCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdjudicatedDate {
            get {
                return this.adjudicatedDateField;
            }
            set {
                this.adjudicatedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdjudicatedStatute {
            get {
                return this.adjudicatedStatuteField;
            }
            set {
                this.adjudicatedStatuteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdjudicatedDescription {
            get {
                return this.adjudicatedDescriptionField;
            }
            set {
                this.adjudicatedDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdjudicatedAcdCode {
            get {
                return this.adjudicatedAcdCodeField;
            }
            set {
                this.adjudicatedAcdCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdjudicatedCustomerCode {
            get {
                return this.adjudicatedCustomerCodeField;
            }
            set {
                this.adjudicatedCustomerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdjudicatedEVC {
            get {
                return this.adjudicatedEVCField;
            }
            set {
                this.adjudicatedEVCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Disposition {
            get {
                return this.dispositionField;
            }
            set {
                this.dispositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StateSpecific")]
        public StateSpecificItemType[] StateSpecific {
            get {
                return this.stateSpecificField;
            }
            set {
                this.stateSpecificField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomerSpecific")]
        public CustomerSpecificItemType[] CustomerSpecific {
            get {
                return this.customerSpecificField;
            }
            set {
                this.customerSpecificField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UncomputedStatuteIndicator {
            get {
                return this.uncomputedStatuteIndicatorField;
            }
            set {
                this.uncomputedStatuteIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ViolationSubRank {
            get {
                return this.violationSubRankField;
            }
            set {
                this.violationSubRankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DowngradeIndicator {
            get {
                return this.downgradeIndicatorField;
            }
            set {
                this.downgradeIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public oAddress Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public oLicensePlate LicensePlate {
            get {
                return this.licensePlateField;
            }
            set {
                this.licensePlateField = value;
            }
        }
        
        /// <remarks/>
        public oDriversLicense DriversLicense {
            get {
                return this.driversLicenseField;
            }
            set {
                this.driversLicenseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class oSubject {
        
        private oDriverViolation[] driverViolationField;
        
        private string numberField;
        
        private string subjectVerifiedField;
        
        private string subjectDriverRankField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DriverViolation")]
        public oDriverViolation[] DriverViolation {
            get {
                return this.driverViolationField;
            }
            set {
                this.driverViolationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SubjectVerified {
            get {
                return this.subjectVerifiedField;
            }
            set {
                this.subjectVerifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SubjectDriverRank {
            get {
                return this.subjectDriverRankField;
            }
            set {
                this.subjectDriverRankField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class oAllViolationSummary {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class oInfo {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class oWarning {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubjectSearchResults))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class BaseResults {
        
        private string searchIDField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string referenceField;
        
        private string trackingNumberField;
        
        private string requestIDField;
        
        private string[] productCodesField;
        
        private oWarning[] warningMessagesField;
        
        private oInfo[] infoMessagesField;
        
        private oAllViolationSummary[] allViolationSummaryField;
        
        private string calculatedLookBackStartDateField;
        
        private string calculatedLookBackEndDateField;
        
        private string usePurposeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SearchID {
            get {
                return this.searchIDField;
            }
            set {
                this.searchIDField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ProductCode")]
        public string[] ProductCodes {
            get {
                return this.productCodesField;
            }
            set {
                this.productCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Warning")]
        public oWarning[] WarningMessages {
            get {
                return this.warningMessagesField;
            }
            set {
                this.warningMessagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Info")]
        public oInfo[] InfoMessages {
            get {
                return this.infoMessagesField;
            }
            set {
                this.infoMessagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AllViolationSummary")]
        public oAllViolationSummary[] AllViolationSummary {
            get {
                return this.allViolationSummaryField;
            }
            set {
                this.allViolationSummaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CalculatedLookBackStartDate {
            get {
                return this.calculatedLookBackStartDateField;
            }
            set {
                this.calculatedLookBackStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CalculatedLookBackEndDate {
            get {
                return this.calculatedLookBackEndDateField;
            }
            set {
                this.calculatedLookBackEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UsePurposeCode {
            get {
                return this.usePurposeCodeField;
            }
            set {
                this.usePurposeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class SubjectSearchResults : BaseResults {
        
        private oSubject[] subjectField;
        
        private string driverRankField;
        
        private oStandardizedAddress[] standardizedAddressesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Subject")]
        public oSubject[] Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DriverRank {
            get {
                return this.driverRankField;
            }
            set {
                this.driverRankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("StandardizedAddress")]
        public oStandardizedAddress[] StandardizedAddresses {
            get {
                return this.standardizedAddressesField;
            }
            set {
                this.standardizedAddressesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class iDriversLicense {
        
        private string numberField;
        
        private string stateCodeField;
        
        private string countryCodeField;
        
        private string sourceField;
        
        private string statusField;
        
        private string endorsementsField;
        
        private string issueDateField;
        
        private string surrenderDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Endorsements {
            get {
                return this.endorsementsField;
            }
            set {
                this.endorsementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SurrenderDate {
            get {
                return this.surrenderDateField;
            }
            set {
                this.surrenderDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class iDOB {
        
        private string yearField;
        
        private string monthField;
        
        private string dayField;
        
        private string sourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class iAddress {
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateCodeField;
        
        private string zipField;
        
        private string countryCodeField;
        
        private string sourceField;
        
        private string statusField;
        
        private string typeField;
        
        private string occupancyStartDateField;
        
        private string occupancyEndDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OccupancyStartDate {
            get {
                return this.occupancyStartDateField;
            }
            set {
                this.occupancyStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OccupancyEndDate {
            get {
                return this.occupancyEndDateField;
            }
            set {
                this.occupancyEndDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.drivershistory.com/currentVersion6")]
    public partial class iPhone {
        
        private string areaCodeField;
        
        private string exchangeField;
        
        private string suffixField;
        
        private string extensionField;
        
        private string sourceField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AreaCode {
            get {
                return this.areaCodeField;
            }
            set {
                this.areaCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Exchange {
            get {
                return this.exchangeField;
            }
            set {
                this.exchangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SubjectSearchCompletedEventHandler(object sender, SubjectSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubjectSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubjectSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubjectSearchResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubjectSearchResults)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SubjectSearchBasicCompletedEventHandler(object sender, SubjectSearchBasicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubjectSearchBasicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubjectSearchBasicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubjectSearchResults Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubjectSearchResults)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591