//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StableLawFirm
{
    using System;
    using System.Collections.Generic;
    
    public partial class STtblCategory
    {
        public STtblCategory()
        {
            this.STtblBlogs = new HashSet<STtblBlog>();
        }
    
        public int tblCategory_Id { get; set; }
        public string caregory_Name { get; set; }
    
        public virtual ICollection<STtblBlog> STtblBlogs { get; set; }
    }
}
