//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StableLawFirm
{
    using System;
    using System.Collections.Generic;
    
    public partial class STtblComment
    {
        public int Comment_Id { get; set; }
        public string Comment_Text { get; set; }
        public Nullable<System.DateTime> Comment_Date { get; set; }
        public string Comment_By { get; set; }
        public string Comment_Email { get; set; }
        public Nullable<int> Blog_Id { get; set; }
        public Nullable<int> Isapproved { get; set; }
    
        public virtual STtblBlog STtblBlog { get; set; }
    }
}
