//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StableLawFirm
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResult
    {
        public int tblResultId { get; set; }
        public string Result_Text { get; set; }
        public Nullable<System.DateTime> Result_Date { get; set; }
        public string Result_Heading { get; set; }
        public Nullable<int> tblUserId { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
