//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureDriving
{
    using System;
    using System.Collections.Generic;
    
    public partial class blogpost
    {
        public int vcodpost { get; set; }
        public string vtitulo { get; set; }
        public string vcontenido { get; set; }
        public string vimagen { get; set; }
        public string vimgubic { get; set; }
        public string vlabel { get; set; }
        public Nullable<System.DateTime> dfecregi { get; set; }
        public string vestregi { get; set; }
    }
}
