//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureDriving
{
    using System;
    using System.Collections.Generic;
    
    public partial class caso
    {
        public int vcodcaso { get; set; }
        public Nullable<int> vcodusua { get; set; }
        public string vname { get; set; }
        public string vcourt { get; set; }
        public string vtype { get; set; }
        public string vinter { get; set; }
        public Nullable<decimal> ntotal { get; set; }
        public Nullable<decimal> npaid { get; set; }
        public Nullable<decimal> nbalan { get; set; }
        public string vfile { get; set; }
        public string vcom { get; set; }
        public Nullable<System.DateTime> dfecregi { get; set; }
        public string vestregi { get; set; }
    }
}
