//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureDriving
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int vcodcli { get; set; }
        public string vnomcli { get; set; }
        public string vapecli { get; set; }
        public string vdircli { get; set; }
        public string vtelcli { get; set; }
        public Nullable<System.DateTime> vfecnaci { get; set; }
        public Nullable<System.DateTime> dfecregi { get; set; }
        public string vestregi { get; set; }
    }
}
