//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureDriving
{
    using System;
    using System.Collections.Generic;
    
    public partial class court1
    {
        public int ncodcort { get; set; }
        public Nullable<int> ncodusua { get; set; }
        public string nnomcort { get; set; }
        public string vdircort { get; set; }
        public string vtelcort { get; set; }
        public string vdet { get; set; }
        public Nullable<System.DateTime> dfecregi { get; set; }
        public string vestregi { get; set; }
    }
}
