//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureDriving
{
    using System;
    using System.Collections.Generic;
    
    public partial class email
    {
        public int vcodemail { get; set; }
        public string vtitle { get; set; }
        public string vname { get; set; }
        public string vphome { get; set; }
        public string vpcell { get; set; }
        public string vemail { get; set; }
        public string vcboOff1 { get; set; }
        public string vcboOff2 { get; set; }
        public string vcboOff3 { get; set; }
        public string vcboOff4 { get; set; }
        public string vrdbdd1 { get; set; }
        public string vticket { get; set; }
        public string vdate { get; set; }
        public string vcourt { get; set; }
        public string vestlicen { get; set; }
        public string vpoints { get; set; }
        public string vrdbq1 { get; set; }
        public string vrdbq2 { get; set; }
        public string vcomduidwi { get; set; }
        public string vcomment { get; set; }
        public Nullable<System.DateTime> dfecregi { get; set; }
        public string vestregi { get; set; }
    }
}
