//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureDriving
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int vcodusua { get; set; }
        public string vtipo { get; set; }
        public string vnomusua { get; set; }
        public string vcon { get; set; }
        public string vnom { get; set; }
        public string vape { get; set; }
        public string vmail { get; set; }
        public Nullable<System.DateTime> vfecnaci { get; set; }
        public Nullable<System.DateTime> dfecregi { get; set; }
        public string vestregi { get; set; }
    }
}
