//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureDriving
{
    using System;
    using System.Collections.Generic;
    
    public partial class video_usuarios_tipo
    {
        public video_usuarios_tipo()
        {
            this.video_usuarios = new HashSet<video_usuarios>();
        }
    
        public int nusuariotipo { get; set; }
        public string vdescripcion { get; set; }
    
        public virtual ICollection<video_usuarios> video_usuarios { get; set; }
    }
}
