//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureDriving
{
    using System;
    using System.Collections.Generic;
    
    public partial class video_usuarios
    {
        public int ncodusua { get; set; }
        public Nullable<int> nusuariotipo { get; set; }
        public string vfullname { get; set; }
        public string vphone { get; set; }
        public string vcelular { get; set; }
        public string vemail { get; set; }
        public string vcomments { get; set; }
        public string vcon { get; set; }
        public Nullable<System.DateTime> vcreation { get; set; }
        public string vestusuario { get; set; }
        public string vdeleted { get; set; }
        public string Address { get; set; }
        public string NJDL_ { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string EyeColor { get; set; }
        public string Gender { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.DateTime> CourseCompletedDate { get; set; }
    
        public virtual video_usuarios_tipo video_usuarios_tipo { get; set; }
    }
}
