//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NJ_Clients
    {
        public int Id { get; set; }
        public string List_Type { get; set; }
        public string File_Date { get; set; }
        public string Court_Name { get; set; }
        public string CourtDate { get; set; }
        public string L_Name { get; set; }
        public string F_Name { get; set; }
        public string MI { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string ST { get; set; }
        public string ZIP { get; set; }
        public string DOB { get; set; }
        public string Violation { get; set; }
        public string Description { get; set; }
        public string DateIssued { get; set; }
        public string Salutation { get; set; }
        public string Summons { get; set; }
        public Nullable<bool> IsUser { get; set; }
        public string NJ_CourtID { get; set; }
        public string Muncipality { get; set; }
        public string Complaint { get; set; }
        public string Title { get; set; }
        public string Payment_Type { get; set; }
        public Nullable<double> Payment_Total { get; set; }
        public Nullable<double> Payment_Paid { get; set; }
        public Nullable<double> Payment_Balance { get; set; }
        public Nullable<System.DateTime> MarkClientDate { get; set; }
        public string Payment_Cardno { get; set; }
        public string Payment_Card_ExpDate { get; set; }
        public Nullable<int> Payment_CVV { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public bool IsPotentialClient { get; set; }
        public bool IsDeleted { get; set; }
        public string Comment { get; set; }
        public Nullable<int> IsAddedBy { get; set; }
        public string SourceOfComm { get; set; }
    }
}
