//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NJ_tblComment
    {
        public int Comment_Id { get; set; }
        public string Comment { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Comment_By { get; set; }
        public Nullable<System.DateTime> Comment_Date { get; set; }
    }
}
