//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NJ_UserRole
    {
        public NJ_UserRole()
        {
            this.NJ_User = new HashSet<NJ_User>();
        }
    
        public int Id { get; set; }
        public string UserRole { get; set; }
    
        public virtual ICollection<NJ_User> NJ_User { get; set; }
    }
}
