//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NJ_User
    {
        public int tblUserId { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int tbl_RoleId { get; set; }
    
        public virtual NJ_UserRole NJ_UserRole { get; set; }
    }
}
