//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewJersyTrafficTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategory
    {
        public tblCategory()
        {
            this.tblBlogs = new HashSet<tblBlog>();
        }
    
        public int tblCategory_Id { get; set; }
        public string Caregory_Name { get; set; }
    
        public virtual ICollection<tblBlog> tblBlogs { get; set; }
    }
}
