//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StabileResults
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StabileLawFirmEntities : DbContext
    {
        public StabileLawFirmEntities()
            : base("name=StabileLawFirmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<STtblBlog> STtblBlogs { get; set; }
        public DbSet<STtblCategory> STtblCategories { get; set; }
        public DbSet<STtblComment> STtblComments { get; set; }
        public DbSet<STtblResult> STtblResults { get; set; }
        public DbSet<STtblUser> STtblUsers { get; set; }
        public DbSet<STtblUserRole> STtblUserRoles { get; set; }
    }
}
