//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StabileResults 
{
    using System;
    using System.Collections.Generic;
    
    public partial class STtblUser
    {
        public STtblUser()
        {
            this.STtblBlogs = new HashSet<STtblBlog>();
            this.STtblResults = new HashSet<STtblResult>();
        }
    
        public int tblUserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> tblUserRoleId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<STtblBlog> STtblBlogs { get; set; }
        public virtual ICollection<STtblResult> STtblResults { get; set; }
        public virtual STtblUserRole STtblUserRole { get; set; }
    }
}
